from __future__ import annotations
from typing import TYPE_CHECKING
import requests
import re
import polars as pl

import lxml.etree
import numpy as np
import pandas as pd

from collections import Counter

try:
    import cld3
    DEFAULT_CLD = 'cld3'
except ModuleNotFoundError:
    DEFAULT_CLD = 'pycld2'
import pycld2


if TYPE_CHECKING:
    from language_tool_python import LanguageTool

WORD_PATT = re.compile(r'\b[^\W\d_]+?\b')

# COLUMNS NAMES:
# user_id
# text
# source

# min number of words to have a valid tweet on which calling the lang detector here (after cleaning) is 4


def clean(tweets_df, text_col='text', acc_th=0.9, min_nr_words=4, min_nr_cjk=4,
          lang=None):
    '''
    From a DataFrame of tweets, detects the language of the text contained in
    'text_col' and output the result in new columns. Before calling a langauge
    detector, the text is pre-processed to rid it of hashtags, usernames in
    mentions and urls. Also, after these are removed, if the remaining text
    is strictly less than 'min_nr_words' words long, we don't bother calling the
    language detector, which will be unreliable anyway.
    '''
    try:
        tweets_lang_df = tweets_df.copy()
        # Match anything starting with @ or # followed by one or more word
        # characters, and which is between word boundaries or at the start or end of
        # the string.
        hash_at_pattern = r'(?:^|\B)((@|#)\w+)(?:$|\b)'
        # Match anything containing /t.co/ surrounded by non-whitespace characters
        # and which is between whitespaces or at the start or end of the string. May
        # be better with all http options at the start, here's it's pretty loose.
        url_pattern = r'(?:^|\s)(\S+\/t.co\/\S+)(?:$|\b)'
        regex_filter = re.compile('({})|({})'.format(hash_at_pattern, url_pattern))
        tweets_lang_df['filtered_text'] = tweets_lang_df[text_col].str.replace(
            regex_filter, '', regex=True)
        foursquare_mask = tweets_lang_df['source'].str.contains('foursquare')
        im_at_mask = tweets_lang_df['text'].str.startswith("I'm at ")
        # These tweets are generated by Foursquare based on people's location, so
        # they don't tell us anything about the user's language.
        tweets_lang_df.loc[foursquare_mask & im_at_mask, 'filtered_text'] = ''
        # Tweets generated by Foursquare can also end with '(@ <location>)', so we
        # get rid of this part which is useless for language detection, as proper
        # nouns just confuse the detector.
        tweets_lang_df.loc[foursquare_mask, 'filtered_text'] = (
            tweets_lang_df.loc[foursquare_mask, 'filtered_text']
                        .str.replace(r'\(@ .*$', '', regex=True)
        )
        # Tweets generated by Instagram can end with ' @ <location>', so we
        # get rid of this part which is useless for language detection, as proper
        # nouns just confuse the detector.
        insta_mask = tweets_lang_df['source'].str.contains('instagram')
        tweets_lang_df.loc[insta_mask, 'filtered_text'] = (
            tweets_lang_df.loc[insta_mask, 'filtered_text']
                        .str.replace(r' @ .*$', '', regex=True)
        )
        # Tweets generated by Path can contain information about the location
        # (after a 'at') and/or the people the user was with (after a 'with'). This
        # metadata is either in parentheses after the core of the tweet, or, if
        # there's is no core text, right at the start without parentheses. Thus we
        # extract only the core text from what's before a '(at' or '(with'.
        path_mask = tweets_lang_df['source'].str.contains('path')
        tweets_lang_df.loc[path_mask, 'filtered_text'] = (
            tweets_lang_df.loc[path_mask, 'filtered_text']
                        .str.extract(r'(.*)(?:\(with|\(at)', expand=False)
        )
        # Extract returns NaN if there's no match, so we need to convert these
        # to the empty string to avoid errors.
        tweets_lang_df.loc[tweets_lang_df['filtered_text'].isnull(),
                        'filtered_text'] = ''
        # A word is defined by the shortest string of letters between two word
        # boundaries, but a letter here is not simply a-z, because we also want to
        # account for non latin alphabets. A letter is then what is neither a digit
        # (\d), nor an underscore, nor a non-word character (\W: punctuation,
        # special characters, emojis...).
        tweets_lang_df['nr_words'] = tweets_lang_df['filtered_text'].str.count(WORD_PATT)
        # We also count the number of Chinese-Japanese-Korean (CJK) characters,
        # because they can be a full word or syllable, and a whole sentence can be
        # written without any space, so the word count is irrelevant.
        cjk_chars_pattern = re.compile(r'[\u4E00-\u9FFF]')
        nr_cjk_chars = tweets_lang_df['filtered_text'].str.count(cjk_chars_pattern)
        long_enough = (tweets_lang_df['nr_words'] >= min_nr_words) | (nr_cjk_chars >= min_nr_cjk)
        if long_enough.any():
            (tweets_lang_df.loc[long_enough, 'cld_lang'],
            tweets_lang_df.loc[long_enough, 'proba']) = zip(
                *tweets_lang_df.loc[long_enough, 'filtered_text'].apply(make_predict))
            mask = tweets_lang_df['proba'] >= acc_th
            if lang is not None:
                lang_mask = tweets_lang_df['cld_lang'] == lang
                mask = mask & lang_mask
            tweets_lang_df = tweets_lang_df.loc[mask]
            tweets_lang_df['filtered_text'] = tweets_lang_df['filtered_text'].str.strip()
        else:
            cols = tweets_lang_df.columns.tolist() + ['cld_lang', 'proba']
            tweets_lang_df = pd.DataFrame(columns=cols)
    except AttributeError:
        cols = tweets_lang_df.columns.tolist() + ['cld_lang', 'proba']
        tweets_lang_df = pd.DataFrame(columns=cols)
    return tweets_lang_df.drop(columns=['source'])


def make_predict(text: str, cld: str = DEFAULT_CLD, langs_agg_dict=None):
    '''
    From a string of text, gets the language detection from one of the CLD
    versions, and unpacks the results in a dictionary.
    '''
    if langs_agg_dict is None:
        langs_agg_dict = {}
    if  cld == 'cld3':
        try:
            raw_predict = cld3.get_language(text)
            lang = raw_predict.language
            proba = raw_predict.probability
        except cld3.error:
            lang = None
            proba = 0
    elif cld == 'pycld2':
        # Sometimes there remain utf code like \x92, which makes pycld2 return
        # an error, so we skip these tweets (there are very few of them)
        try:
            raw_predict = pycld2.detect(text)
            lang = raw_predict[2][0][1]
            proba = raw_predict[2][0][2] / 100
        except pycld2.error:
            lang = None
            proba = 0
    # The following is for if the lang is to be aggregated with a similar one.
    # For instance, we might like to aggregate to Chinese ('zh') its traditional
    # form ('zh-Hant').
    agg_to_lang = langs_agg_dict.get(lang)
    if agg_to_lang is not None:
        lang = agg_to_lang
    return lang, proba


def count_mistakes(
    user_corpora: pd.DataFrame, language_tool: LanguageTool
) -> pd.DataFrame:
    '''
    From `user_corpora`, which has `user_id` as Index and a 'text' column containing the
    corpus of tweets corresponding to each user, detect with the `language_tool`
    instance the mistakes made by this user, and then store in `user_mistakes` the
    number of times each user made an error corresponding to a given rule and its
    category. 

    Another simpler way to create `user_mistakes` would simply be to iterate and append
    some lists for every match, but this is nicer because it does not duplicate data
    like `user_id`s, which are very long.
    '''
    # start the server here?
    multiindex_dict = {
        # if really want to save disk space, can do:
        # 'levels': [np.arange(user_corpora.index.size), [], []],
        # and the user_id level values will correspond to the index iloc in user_corpora
        #'levels': [user_corpora.index.values, [], []],
        'levels': [user_corpora.user_id, [], []],
        'codes': [[], [], []],
        'names': ['user_id', 'category', 'rule_id']
    }
    # Store code correspondance as a dict for each attribute, in the format `attr_value:
    # attr_code`
    code_corr = {attr_name: {} for attr_name in multiindex_dict['names'][1:]}
    for iloc_user, utuple in enumerate(user_corpora.itertuples()):
        print('iloc_user', iloc_user)
        print('utuple', utuple)
        # If too much text for single user, split into chunks to make smaller queries
        # to LT server.
        if len(utuple.text) > 2e4: # 5000 words of 4 characters
            matches = []
            sentences_sets = utuple.text.splitlines(keepends=True)
            nr_words_per_tweet = utuple.nr_words / utuple.nr_tweets
            # roughly have 1000 tweets of 5 words
            n_splits = int(len(sentences_sets) // (5000 / nr_words_per_tweet))
            for i in range(n_splits):
                matches.extend(language_tool.check(
                    ''.join(sentences_sets[i::n_splits])
                ))
        else:
            matches = language_tool.check(utuple.text)
        multiindex_dict['codes'][0].extend(len(matches) * [iloc_user])
        for m in matches:
            for i_attr, attr_name in enumerate(code_corr.keys(), start=1):
                attr_value = getattr(m, attr_name)
                # If it's the first time we encounter this attribute's value, add a new
                # item in `code_corr` and append this value to the levels.
                if attr_value not in code_corr[attr_name]:
                    code_corr[attr_name][attr_value] = len(code_corr[attr_name])
                    multiindex_dict['levels'][i_attr].append(attr_value)
                code = code_corr[attr_name][attr_value]
                multiindex_dict['codes'][i_attr].append(code)

    user_mistakes = (
        pd.DataFrame({'count': True}, index=pd.MultiIndex(**multiindex_dict))
         .groupby(multiindex_dict['names'])
         .sum()
    )

    ses_map = user_corpora.set_index("user_id")["SES_users"]

    user_mistakes["SES_users"] = (
        user_mistakes.index.get_level_values("user_id")
        .map(ses_map)
    )

    return user_mistakes

def count_mistakes_single_tweets(tweets_df, language_tool):

    # start the server here?
    multiindex_dict = {
        # if really want to save disk space, can do:
        # 'levels': [np.arange(user_corpora.index.size), [], []],
        # and the user_id level values will correspond to the index iloc in user_corpora
        #'levels': [user_corpora.index.values, [], []],
        'levels': [tweets_df.tweet_id, [], []],
        'codes': [[], [], []],
        'names': ['tweet_id', 'category', 'rule_id']
    }
    # Store code correspondance as a dict for each attribute, in the format `attr_value:
    # attr_code`
    code_corr = {attr_name: {} for attr_name in multiindex_dict['names'][1:]}
    for iloc_tweet, utuple in enumerate(tweets_df.itertuples()):

        # If too much text for single user, split into chunks to make smaller queries
        # to LT server.
        '''if len(utuple.text) > 2e4: # 5000 words of 4 characters
            matches = []
            sentences_sets = utuple.text.splitlines(keepends=True)
            nr_words_per_tweet = utuple.nr_words / utuple.nr_tweets
            # roughly have 1000 tweets of 5 words
            n_splits = int(len(sentences_sets) // (5000 / nr_words_per_tweet))
            for i in range(n_splits):
                matches.extend(language_tool.check(
                    ''.join(sentences_sets[i::n_splits])
                ))
        else:'''
        matches = language_tool.check(utuple.text)
        multiindex_dict['codes'][0].extend(len(matches) * [iloc_tweet])
        for m in matches:
            for i_attr, attr_name in enumerate(code_corr.keys(), start=1):
                attr_value = getattr(m, attr_name)
                # If it's the first time we encounter this attribute's value, add a new
                # item in `code_corr` and append this value to the levels.
                if attr_value not in code_corr[attr_name]:
                    code_corr[attr_name][attr_value] = len(code_corr[attr_name])
                    multiindex_dict['levels'][i_attr].append(attr_value)
                code = code_corr[attr_name][attr_value]
                multiindex_dict['codes'][i_attr].append(code)

    user_mistakes = (
        pd.DataFrame({'count': True}, index=pd.MultiIndex(**multiindex_dict))
         .groupby(multiindex_dict['names'])
         .sum()
    )
    
    user_map = tweets_df.set_index("tweet_id")['user_id']
    ses_map = tweets_df.set_index('tweet_id')['SES_users']

    user_mistakes['user_id'] = (
        user_mistakes.index.get_level_values('tweet_id')
        .map(user_map)
    )

    user_mistakes['SES_users'] = (
        user_mistakes.index.get_level_values('tweet_id')
        .map(ses_map)
    )

    return user_mistakes
    '''dict_matches = {}

    for i in range(len(tweets_df)):
        user_id = tweets_df.at[i, 'user_id']
        tweet_id = tweets_df.at[i, 'id']
        if user_id not in dict_matches.keys():
            dict_matches[user_id] = {}
            dict_matches[user_id][tweet_id] = {}
        else:
            dict_matches[user_id][tweet_id] = {}
        matches = language_tool.check(tweets_df.text)
        for m in matches:

            for i_attr, attr_name in enumerate(code_corr.keys())'''


def measure_vocab_size(t: str):
    return len(set(re.findall(WORD_PATT, t)))


def yearly_vocab(user_corpora: pd.DataFrame, words_index: pd.Series):
    '''
    Because unique is not parallelisable, have to do it this way. Reduce rank list sizes
    using the 'words_until' column
    `words_index` sorted by decreasing word's freq, 
    '''
    user_words = (
        user_corpora['text'].str.lower()
         .str.findall(WORD_PATT)
         .explode()
         .rename('word')
         .to_frame()
         .groupby(['user_id', 'word'])
         .size()
         .rename('count')
    )
    user_words = user_words.to_frame().join(words_index.rename('rank'))

    nr_words = words_index.size
    first_time = not 'rank_arr' in user_corpora.columns
    list_arr = []
    list_until = []
    for user_id, g in user_words['rank'].groupby('user_id'):

        if first_time:
            start_new_rank = nr_words
            sorted_ranks = np.sort(g.values)

        else:
            user_rank_arr = user_corpora.loc[user_id, 'rank_arr']
            if isinstance(user_rank_arr, list):
                start_new_rank = max(nr_words, user_rank_arr[-1])
                sorted_ranks = np.sort(np.unique(np.append(user_rank_arr, g.values)))
            else:
                start_new_rank = nr_words
                sorted_ranks = np.sort(g.values)

        is_word_only_instance = np.isnan(sorted_ranks)
        sorted_ranks[is_word_only_instance] = (
            is_word_only_instance[is_word_only_instance].cumsum() + start_new_rank
        )
        sorted_ranks = sorted_ranks.astype(int)
        is_consec = np.diff(sorted_ranks) == 1
        consec_until = 0 if is_consec.size == 0 else is_consec.argmin()
        if consec_until == 0:
            all_until = None
            user_rank_arr = sorted_ranks
        else:
            all_until = sorted_ranks[consec_until]
            user_rank_arr = sorted_ranks[consec_until + 1:]
        list_until.append(all_until)
        list_arr.append(list(user_rank_arr))

    idx_users_with_data = user_words.index.levels[0][np.unique(user_words.index.codes[0])]
    user_corpora.loc[idx_users_with_data, 'words_until'] = list_until
    user_corpora.loc[idx_users_with_data, 'rank_arr'] = list_arr
    return user_corpora


def parse_grammar(source):
    print("Parsing...")
    if source.startswith('http'):
        source = requests.get(source).content
        tree = lxml.etree.fromstring(source)
    else:
        tree = lxml.etree.parse(source)

    list_cats = []
    for cat in tree.iterfind('category'):
        cat_dict = {**cat.attrib}
        # cat_dict['rule_groups'] = [
        #     {'id': rule.attrib['id'], 'rules': [{**rule.attrib}]}
        #     for rule in cat.iterfind('rule')
        # ]
        # cat_dict['rule_groups'].extend([
        #     {**rg.attrib, 'rules': [{**r.attrib} for r in rg.iterfind('rule')]}
        #     for rg in cat.iterfind('rulegroup')
        # ])
        cat_dict['rules'] = [
            {**rule.attrib, 'is_rule_group': False}
            for rule in cat.iterfind('.//rule')
            if 'id' in rule.attrib
        ]
        # rulegroups are not actually a level above rules, the rules they contain do not
        # have an ID
        cat_dict['rules'].extend([
            {**rg.attrib, 'is_rule_group': True}
            for rg in cat.iterfind('rulegroup')
        ])
        list_cats.append(cat_dict)

    nr_rules = sum([len(c['rules']) for c in list_cats])
    print(f'Found {len(list_cats)} categories containing {nr_rules} rules.')
    return list_cats


def parse_online_grammar(lc):
    # remain rules written in java () not in grammar.xml...
    # https://github.com/languagetool-org/languagetool/blob/master/languagetool-language-modules/{lc}/src/main/java/org/languagetool/rules/{lc}/*Rule.java.
    #  But almost neer a category in those, so...
    print("Downloading grammar from LT's repo for parsing...")
    url_format = "https://raw.githubusercontent.com/languagetool-org/languagetool/master/languagetool-language-modules/{lc}/src/main/resources/org/languagetool/rules/{lc}/grammar.xml"
    source = url_format.format(lc=lc)
    list_cats = parse_grammar(source)
    lt_cats_dict = {'categories': list_cats, 'source': source}
    return lt_cats_dict


def get_lt_rules(lt_cats_dict):
    lt_rules = (
        pd.DataFrame
         .from_records(lt_cats_dict['categories'], columns=['id', 'rules'])
         .explode('rules')
    )
    lt_rules = (
        pd.DataFrame.from_records(
            lt_rules['rules'].values.tolist(), index=lt_rules.index
        )
         .join(lt_rules['id'].rename('cat_id').drop_duplicates())
         .set_index('id')
         .rename_axis('rule_id')
    )

    return lt_rules


def get_lt_categories(lt_cats_dict):
    lt_categories = (
        pd.DataFrame
         .from_records(lt_cats_dict['categories'], exclude=['rules'])
         .set_index('id')
    )
    return lt_categories


# MY FUNCTIONS

def merge_user_tweets(tweets_df: pd.DataFrame):
    '''
    Given a set of tweets related to users, it merges them by user_id (used as index) into a 
    string where each tweet is separated by \n from the others, it creates the input df for 
    `count_mistakes` function
    '''

    user_corpora = (
    tweets_df
    .groupby("user_id")
    .agg(
        text=("filtered_text", "\n".join),
        nr_words=("filtered_text", lambda s: s.str.split().str.len().sum()),
        nr_tweets=("filtered_text", "count")
        )
    )

    return user_corpora


def cld3_detect(text, threshold):
    try:
        result = cld3.get_language(text)
        if result is None:
            return None
        if result.probability < threshold:
            return None
        return result.language  # returns ISO 639-1 code, e.g., "en", "fr"
    except:
        return None


def majority_language_twitter(text, twitter_lang, threshold):
    cld3_lang = cld3_detect(text, threshold)
    
    # votes: Twitter + CLD3
    votes = [l for l in [twitter_lang, cld3_lang] if l is not None]
    
    if not votes:
        return None
    
    most_common, freq = Counter(votes).most_common(1)[0]
    
    # Require at least 2 votes agreeing → here only 2 sources, so freq must be 2
    return most_common if freq >= 2 else None


    

def clean_tweet(tweet_df, text_col):
    '''
    Given a tweet, it cleans its text in two different ways:
    1) to get the input for the classification model: remove mentions, URLs, and autogenerated text, while keep hashtags, emoji
    2) to get the input for the language detector
    It also counts the number of words in the cleaned text
    '''

    tweet_df = tweet_df.with_columns([

        # 1) Light cleaning: remove URLs and mentions only
        pl.col(text_col)
        .str.replace_all(r"https?://\S+|www\.\S+", "")
        .str.replace_all(r"@\w+", "")
        .str.replace_all(r"\s+", " ")
        .str.strip_chars()
        .alias("clean_classifier"),

        # 2) Full cleaning: remove URLs, mentions, hashtags, emojis, punctuation
        pl.col(text_col)
        .str.to_lowercase()
        .str.replace_all(r"https?://\S+|www\.\S+", "")
        .str.replace_all(r"@\w+", "")
        .str.replace_all(r"#\w+", "")          # remove hashtag + word
        .str.replace_all(r"[^\x00-\x7F]+", "") # remove emojis
        .str.replace_all(r"[^\w\s]", "")       # remove punctuation
        .str.replace_all(r"\s+", " ")
        .str.strip_chars()
        .alias("clean_lang_detect")

    ]).with_columns([

    # word count for classifier cleaning
    pl.col("clean_classifier")
    .str.split(" ")
    .list.len()
    .alias("num_words_classifier"),

    # word count for lang detection cleaning
    pl.col("clean_lang_detect")
    .str.split(" ")
    .list.len()
    .alias("num_words_lang_detect")

    ])

    return tweet_df

    




def remove_accents(name):
    '''
    Given a string, it removes the accents
    :param name: word str
    :return:
    '''

    name = re.sub('á','a', name)
    name = re.sub('é','e', name)
    name = re.sub('í','i', name)
    name = re.sub('ó','o', name)
    name = re.sub('ú','u', name)
    name = re.sub('ý','y', name)
    name = re.sub('à','a', name)
    name = re.sub('è','e', name)
    name = re.sub('ì','i', name)
    name = re.sub('ò','o', name)
    name = re.sub('ù','u', name)
    name = re.sub('ä','a', name)
    name = re.sub('ë','e', name)
    name = re.sub('ï','i', name)
    name = re.sub('ö','o', name)
    name = re.sub('ü','u', name)
    name = re.sub('ÿ','y', name)
    name = re.sub('â','a', name)
    name = re.sub('ê','e', name)
    name = re.sub('î','i', name)
    name = re.sub('ô','o', name)
    name = re.sub('û','u', name)
    name = re.sub('ã','a', name)
    name = re.sub('õ','o', name)
    name = re.sub('ñ','n', name)

    return name


def remove_special(my_string, weird_words):
    '''
    Remove special characters (non alphanumeric) and weird words
    :param my_string: string
    :param weird_words: weird words list
    :return:
    '''

    #my_string = unidecode.unidecode(my_string)  # eliminate weird accents
    #my_string = remove_accents(my_string)
    #my_string = re.sub(r'[^a-zA-Z0-9А-яء-ي]+', ' ', my_string)  # eliminate what is not letter or number

    my_string = my_string.lower()
    for c in my_string:
        if not (c.isalpha() or c.isdigit() or c == ' '):
            my_string = my_string.replace(c, ' ')
    my_string = re.sub(' +', ' ', my_string)
    for word in weird_words: # TODO decidere come toglierle e queli -> cosa fare se sono sottostringhe di parole? se servissero?
        if word in my_string:
            my_string = my_string.replace(word, ' ')
    my_string = re.sub(' +', ' ', my_string)
    my_string = my_string.strip()
    if my_string == ' ':
        my_string = my_string.replace(' ', '')

    return my_string


def transform_emoji(my_string, list_flags):
    '''
    Keep only flags emojis, remove others
    :param my_string: string
    :param list_flags: list of flags
    :return:
    '''

    # run only once after installing module
    #demoji.download_codes()

    em = demoji.findall(my_string)

    for e in em:
        if em[e] in (list_flags):
            my_string = my_string.replace(e, ' ' + em[e][6:] + ' ')
        else:
            my_string = my_string.replace(e, ' ')

    return my_string


def remove_emoji(my_string):
    '''
    Remove all emojis
    :param my_string: string
    :return:
    '''

    em = demoji.findall(my_string)

    for e in em:
        my_string = my_string.replace(e, ' ')
    
    return my_string




def cleaning_nominatim(starting_location, list_flags, weird_words):
    '''
    Given a starting location, a list of flags, and a list of weird words, it returns the cleaned location
    :param starting_location: string of sarting location
    :param list_flags: list of flags
    :param weird_words: list of weird words
    :return: cleaned location
    '''

    cleaned_loc = transform_emoji(starting_location, list_flags)
    cleaned_loc = remove_special(cleaned_loc, weird_words)

    return cleaned_loc



def cleaning(location_dataset, unicodes_flags_dataset, weird_words_dataset, output_file):
    '''
    Given the dataset with locations, the flags unicodes, the weird words, it does the locations cleaning
    :param location_dataset: path of dataset of locations
    :param unicodes_flags_dataset: path of dataset of unicodes flags
    :param weird_words_dataset: path of dataset of weird words
    :param output_file: path of output file
    :return: cleaned dataset of locations
    '''

    df_unicodes = pd.read_csv(unicodes_flags_dataset, sep='\t')
    list_flags = list(df_unicodes['country_code'])

    df_loc = pd.read_csv(location_dataset, sep='\t')

    df_weird_words = pd.read_csv(weird_words_dataset)
    weird_words = list(df_weird_words['word'])

    cleaned_localities = []

    for loc in df_loc['location'].values:
        if not pd.isna(loc):
            loc = transform_emoji(loc, list_flags)
            loc = remove_special(loc, weird_words)
        cleaned_localities.append(loc)

    df_loc['cleaned_loc'] = cleaned_localities

    df_loc.to_csv(output_file, sep='\t', index=False)

    return df_loc


def cleaning_ner_loc(my_string, list_flags):
    '''
    It computes cleaning on tweet field location for NER
    :param my_string: location string
    :param list_flags: list of flags
    :return: cleaned string
    '''

    my_string = transform_emoji(my_string, list_flags)
    my_string = my_string.replace('|', ',')
    my_string = re.sub(' +', ' ', my_string)
    my_string = my_string.strip()
    if my_string == ' ':
        my_string = my_string.replace(' ', '')

    return my_string


def replace_URL(text):
    '''
    It replaces url address with "URL"
    :param text: text
    :return: cleaned text
    '''

    text = re.sub('((www\.[^\s]+)|(https?://[^\s]+))', 'URL', text)
    text = re.sub(r'#([^\s]+)', r'\1', text)
    print('prova', text)

    return text


def replace_URL_empty(text):
    '''
    It replaces url address with "URL"
    :param text: text
    :return: cleaned text
    '''

    text = re.sub('((www\.[^\s]+)|(https?://[^\s]+))', '', text)
    text = re.sub(r'#([^\s]+)', r'\1', text)

    return text


def replace_mention(text):
   '''
   It replaces mentions with "_MENTION_"
   :param text: text
   :return: text with mentions replaced with "_MENTION_"
   '''

   return re.sub("@[A-Za-z0-9_]+", "_MENTION_", text)


def replace_mention_empty(text):
    '''
    It replaces mentions with " "
    :param text: text
    :return: 
    '''

    return re.sub("@[A-Za-z0-9_]+", " ", text)


def find_hashtag(text):
    '''
    It returns hashtags in a tweet
    :param text: text
    :return: text splitted where there are hashtags
    '''

    return set([el for el in text.split() if el.startswith("#")])


def preprocess_tweet_text(text, lang): # it puts everything to lower case -> we use this only on hshtags
    '''
    It preprocesses the tweet text, we use it only on hastags (it divides words in hashtags) after havin extracted them
    since we want to keep the text as given to extract Named Entities
    :param text: text
    :param lang: text's language (but we set English since is the one we know that works -> check it with FBK)
    :return:
    '''

    # todo check possible len
    url = "https://dh.fbk.eu/dh-ppp"
    headers = {"Content-Type": "text/json"}

    text = text.strip("\n")
    parts = text.split("\t")
    dataDict = dict()
    dataDict["text"] = parts[0]
    dataDict["lang"] = lang # 'en'  # sono disponibili circa 10 lingue ma non per tutte c'è la lemmatizzazione nella parte delle emozioni
    r = requests.post(url, data=json.dumps(dataDict), headers=headers)
    a = r.json()

    return a['preprocessedText']


def clean_tweet_text(text, list_flags, tweet_lang):
    '''
    It computes cleaning on tweet text (split hashtags, transform flags emoji, replace URLs, replace mentions)
    :param text: text
    :param list_flags: list of flags
    :param tweet_lang: tweet's language
    :return
    '''

    dict_hashtags = find_hashtag(text)
    for el in dict_hashtags:
        text = text.replace(el, preprocess_tweet_text(el, tweet_lang))
    text = transform_emoji(text, list_flags)
    text = replace_URL(text)
    text = replace_mention(text)
    text = re.sub(' +', ' ', text)
    text = text.strip()

    return text


def split_hashtag(text):
    '''
    It removes '#' and splits hashtags words
    :param text:
    :return:
    '''
    # todo -> deal with hashtags with no capital letters
    return re.sub(r'#[a-z]\S*|#[A-Z]\S*', lambda m: ' '.join(re.findall('[A-Z][^A-Z]*|[a-z][^A-Z]*', m.group().lstrip('#'))), text,)


def clean_tweet_ner_loc(text):
    '''
    Clean text for NER
    :param text: text
    :return:
    '''

    text = remove_emoji(text)
    text = replace_URL_empty(text)
    text = replace_mention(text)
    text = split_hashtag(text)
    text = re.sub(' +', ' ', text)
    text = text.strip()

    return text


def clean_tweet_topics(df, text_col, location_col):
    '''
    Clean tweets text to have input for topics (everything already in lower case and no empty tweet text): remove locations, URLs, emojis, user mentions, hashtag symbols
    :param df: dataframe tweets
    :param text_col: tweet text column
    :param location_col: tweet location column
    :return:
    '''

    # create cleaned text column as an empty column
    df['cleaned_text'] = pd.Series(dtype='str')

    for i in range(len(df)):

        text = df.at[i, text_col]
        loc = df.at[i, location_col]

        # remove extra spaces
        text = re.sub(' +', ' ', text)
        # remove URLs
        text = replace_URL_empty(text)
        # remove emojis
        text = remove_emoji(text)
        # remove mentions
        text = replace_mention_empty(text)
        # remove hashtags
        text = split_hashtag(text)
        # remove locations
        if not pd.isna(loc):
            text = text.replace(loc, ' ')

        df.at[i, 'cleaned_text'] = text

    return df
